export const styles = {
  screen: {
    minHeight: '100vh',
    backgroundColor: '#080f1e',
    maxWidth: '480px',
    margin: '0 auto',
    paddingBottom: '72px',
  },
  card: {
    backgroundColor: '#0d1b2e',
    borderRadius: '14px',
    border: '0.5px solid #1a2f4a',
    padding: '16px',
    marginBottom: '10px',
    transition: 'background-color 0.15s ease',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
    marginTop: '20px',
  },
  btnPrimary: {
    backgroundColor: '#00d4ff',
    color: '#04091a',
    borderRadius: '10px',
    padding: '13px 20px',
    fontSize: '14px',
    fontWeight: '600',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
    transition: 'background-color 0.15s',
  },
  btnOutline: {
    backgroundColor: 'transparent',
    color: '#00d4ff',
    borderRadius: '10px',
    padding: '12px 20px',
    fontSize: '14px',
    fontWeight: '600',
    border: '1px solid #00d4ff',
    cursor: 'pointer',
    width: '100%',
  },
  btnDanger: {
    backgroundColor: 'transparent',
    color: '#ef4444',
    borderRadius: '10px',
    padding: '12px 20px',
    fontSize: '14px',
    fontWeight: '500',
    border: '1px solid #ef4444',
    cursor: 'pointer',
    width: '100%',
  },
  input: {
    backgroundColor: '#112035',
    color: '#f0f6ff',
    borderRadius: '10px',
    border: '0.5px solid #1a2f4a',
    padding: '12px 14px',
    fontSize: '14px',
    width: '100%',
    outline: 'none',
    boxSizing: 'border-box',
  },
  topNav: {
    position: 'sticky',
    top: 0,
    zIndex: 100,
    backgroundColor: '#04091a',
    borderBottom: '0.5px solid #1a2f4a',
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bottomNav: {
    position: 'fixed',
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: '480px',
    backgroundColor: '#04091a',
    borderTop: '0.5px solid #1a2f4a',
    display: 'flex',
    height: '64px',
    zIndex: 100,
  },
  divider: {
    height: '0.5px',
    backgroundColor: '#1a2f4a',
    border: 'none',
    margin: '8px 0',
  },
  statsCard: {
    backgroundColor: '#0d1b2e',
    borderRadius: '10px',
    border: '0.5px solid #1a2f4a',
    padding: '12px',
    textAlign: 'center',
    flex: 1,
  },
};

export const severityStyle = (severity) => {
  const map = {
    Critical: '#ef4444',
    High:     '#f97316',
    Medium:   '#eab308',
    Low:      '#22c55e',
  };
  const c = map[severity] || '#475569';
  return {
    backgroundColor: c + '1a',
    color: c,
    border: `0.5px solid ${c}40`,
    borderRadius: '999px',
    padding: '3px 10px',
    fontSize: '11px',
    fontWeight: '600',
    display: 'inline-block',
  };
};

export const statusColor = (status) => ({
  'Reported':    '#475569',
  'Verified':    '#3b82f6',
  'In Progress': '#f97316',
  'Resolved':    '#16a34a',
}[status] || '#475569');
